### ISSUE TITLE
Make STL for Mac

### ISSUE THREAD

**Issue by wranglatang** [wbu/drawer_organizer#8]
Hello, I have been looking at what you have created and it looks great! only problem is I'm unable to run the Make STL as it seems to be set up for Windows only. Im on mac, has anyone had a go at making the script run on mac that they could share?

**Comment by wbu** [comment]
So far I have tested the script with Linux only. What error message do you get on your Mac?

**Comment by wranglatang** [comment]
Seems to be a permissions issue when trying to launch OpenSCAD from the python script. I can run it manually to open the application itself. 

``` log
MyAccountName files % python3 ./make_stl.py 
running '/Applications/OpenSCAD.app -o stl/height=10/connector_zero height=10.stl -q --hardwarnings -D part="connector_zero" -D height=10 drawer_organizer.scad'
Traceback (most recent call last):
  File "./make_stl.py", line 75, in <module>
    subprocess.run(cmd, check=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Applications/OpenSCAD.app'
```

**Comment by wbu** [comment]
I don't have a Mac, but you might be using an incomplete application path. Seems like you have to add a path after the .app archive to a executable within it: https://stackoverflow.com/questions/66089719/subprocess-permission-and-no-such-file-or-directory-error-messages

**Comment by wranglatang** [comment]
Hmmm, im not really sure how i would get the contents of the full path to the executable?

**Comment by krakpot** [comment]
@wranglatang Perhaps you've already resolved this but I ran into the same issue. The full path to the executable in `OpenSCAD.app` is `/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD` (You can just `cd` into it if you're in the Terminal or select `Show Package Contents` in the popup menu if you're using Finder)

```diff
drawer_organizer $ git diff
diff --git a/make_stl.py b/make_stl.py
index e4f0499..3841259 100755
--- a/make_stl.py
+++ b/make_stl.py
@@ -5,7 +5,7 @@ import subprocess
 import os
 import json

-EXECUTABLE = "openscad-nightly"
+EXECUTABLE = "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
 OUTPUT_TYPE = "stl" # openscad also supports "amf", "3mf" and others
```


```bash
drawer_organizer $ ./make_stl.py
running '/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o stl/height=25/connector_zero height=25.stl -q --hardwarnings -D part="connector_zero" -D height=25 drawer_organizer.scad'
running '/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o stl/height=25/connector_straight height=25.stl -q --hardwarnings -D part="connector_straight" -D height=25 drawer_organizer.scad'
running '/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o stl/height=25/connector_t height=25.stl -q --hardwarnings -D part="connector_t" -D height=25 drawer_organizer.scad'
```
